export const motivationalQuotes = [
  "The beautiful thing about learning is that no one can take it away from you.",
  "Education is the most powerful weapon which you can use to change the world.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Don't let what you cannot do interfere with what you can do.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Education is not the filling of a pail, but the lighting of a fire.",
  "The expert in anything was once a beginner.",
  "Your time is limited, so don't waste it living someone else's life.",
  "The only way to do great work is to love what you do.",
  "Knowledge is power. Information is liberating. Education is the premise of progress.",
  "Change is the end result of all true learning.",
  "The secret of getting ahead is getting started.",
  "Hard work beats talent when talent doesn't work hard.",
  "It always seems impossible until it's done.",
  "Learning never exhausts the mind.",
  "The direction in which education starts a man will determine his future in life.",
  "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.",
  "An investment in knowledge pays the best interest.",
  "Develop a passion for learning. If you do, you will never cease to grow.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "The roots of education are bitter, but the fruit is sweet.",
  "What we learn with pleasure we never forget.",
  "The purpose of education is to replace an empty mind with an open one.",
  "Education is the movement from darkness to light.",
  "Aim for the moon. If you miss, you may hit a star.",
  "You are never too old to set another goal or to dream a new dream.",
  "The mind is not a vessel to be filled but a fire to be ignited.",
  "If you think education is expensive, try ignorance.",
  "Knowledge will bring you the opportunity to make a difference.",
  "Learning is a treasure that will follow its owner everywhere.",
  "Education is the key to unlocking the world, a passport to freedom.",
  "Don't wait for opportunity. Create it.",
  "Success consists of going from failure to failure without loss of enthusiasm.",
  "The best way to predict your future is to create it.",
  "Every expert was once a beginner.",
  "Formal education will make you a living; self-education will make you a fortune.",
  "The only person who is educated is the one who has learned how to learn and change.",
  "Your attitude, not your aptitude, will determine your altitude.",
  "Great things never come from comfort zones.",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go.",
  "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.",
  "Learning is the only thing the mind never exhausts, never fears, and never regrets.",
  "Whatever you are, be a good one.",
  "Do one thing every day that scares you.",
  "Dream big and dare to fail.",
  "Quality is not an act, it is a habit.",
  "Start where you are. Use what you have. Do what you can.",
  "Education's purpose is to replace an empty mind with an open one.",
  "Genius is 1% inspiration and 99% perspiration.",
  "Opportunities don't happen. You create them.",
  "I find that the harder I work, the more luck I seem to have.",
  "The secret to success is to do the common things uncommonly well.",
  "To handle yourself, use your head; to handle others, use your heart.",
  "If you want to lift yourself up, lift up someone else.",
  "There are no shortcuts to any place worth going.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Knowledge is of no value unless you put it into practice.",
  "The only true wisdom is in knowing you know nothing.",
  "Be curious, not judgmental.",
  "He who opens a school door, closes a prison.",
  "The function of education is to teach one to think intensively and to think critically.",
  "Intelligence plus character - that is the goal of true education.",
  "A person who never made a mistake never tried anything new.",
  "Try to be a rainbow in someone else's cloud.",
  "If you can dream it, you can do it.",
  "The best way to find yourself is to lose yourself in the service of others.",
  "Persistence is to the character of man as carbon is to steel.",
  "The man who does not read has no advantage over the man who cannot read.",
  "Never stop learning, because life never stops teaching.",
  "Every student can learn, just not on the same day, or in the same way.",
  "Teaching is the greatest act of optimism.",
  "Teachers can change lives with just the right mix of chalk and challenges.",
  "The mediocre teacher tells. The good teacher explains. The superior teacher demonstrates. The great teacher inspires.",
  "A teacher affects eternity; he can never tell where his influence stops.",
  "Education is our passport to the future, for tomorrow belongs to the people who prepare for it today.",
  "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
  "Small progress is still progress.",
  "Focus on being productive instead of busy.",
  "The secret of success is consistency of purpose.",
  "Don't stop until you're proud.",
  "You don't have to be perfect to be amazing.",
  "Make today so awesome yesterday gets jealous.",
  "Mistakes are proof that you are trying.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "When we strive to become better than we are, everything around us becomes better too.",
  "Act as if what you do makes a difference. It does.",
  "Believe you can and you're halfway there.",
  "Stay positive, work hard, and make it happen.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "You miss 100% of the shots you don't take.",
  "It's not whether you get knocked down, it's whether you get up.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Hard times don't create heroes. It is during the hard times when the 'hero' within us is revealed.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Courage is resistance to fear, mastery of fear, not absence of fear.",
  "Do what you can, with what you have, where you are.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "The way to get started is to quit talking and begin doing.",
  "Happiness is not something readymade. It comes from your own actions.",
  "Don't count the days, make the days count.",
  "You must be the change you wish to see in the world.",
  "Strength does not come from physical capacity. It comes from an indomitable will.",
  "The weak can never forgive. Forgiveness is the attribute of the strong.",
  "An eye for an eye only ends up making the whole world blind.",
  "First they ignore you, then they laugh at you, then they fight you, then you win.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "In a gentle way, you can shake the world.",
  "The best way to find yourself is to lose yourself in the service of others.",
  "Life is what happens when you're busy making other plans.",
  "You only live once, but if you do it right, once is enough.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "The only way to have a friend is to be one.",
  "If you want to be happy, be.",
  "Everything you've ever wanted is on the other side of fear.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "The power of imagination makes us infinite."
];
